config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'posts#index'
  resources :posts

  get 'search', to: "posts#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  include PgSearch
  pg_search_scope :search_by_title,
                   against: :title,
                   using: {
                    tsearch: {prefix: true}
                   }
  extend FriendlyId
  friendly_id :title, use: :slugged

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize.to_s
  end


  has_one_attached :image

  acts_as_taggable # Alias for acts_as_taggable_on :tags

  belongs_to :user
  validates :title, presence: {message: '必須有標題'}
  validates :content, presence: {message: '必須有內容'}
  validates :brief, presence: {message: '必須有概要'}
  validate :correct_image_type

  private
    def correct_image_type
      if !image.attached?
        errors.add(:image, '必須有封面')
      elsif !image.content_type.in?(%w(image/jpeg image/png ))
        errors.add(:image, '圖片格式須為(jpeg/png)')
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_post, except: [:index, :new, :create, :search]
  before_action :user_correct, except: [:index, :show, :new, :create, :search]

  def search
    if params[:search].present?
      @posts = Post.search_by_title(params[:search]).page(params[:page]).per(6).order("created_at DESC").with_attached_image
      render 'index'
    else
      @posts = Post.page(params[:page]).per(6).order("created_at DESC").with_attached_image
      render 'index'
    end
  end

  def index
    if params[:tag_selected].present?
      @posts = Post.tagged_with(params[:tag_selected], any: true).page(params[:page]).per(6).order("created_at DESC").with_attached_image
    else
      @posts = Post.page(params[:page]).per(6).order("created_at DESC").with_attached_image
      #with_attached_image 避免ActiveStorage n+1問題
    end
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = '已發布!'
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      flash[:success] = '已編輯!'
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:danger] = '已刪除!'
    redirect_to posts_url
  end

  private
    def post_params
      params.require(:post).permit(:title, :brief, :content, :image, :tag_list)
    end
    def set_post
      @post = Post.friendly.find(params[:id])
    end
    def user_correct
      unless post_owner?
        flash[:danger] = '沒有權限'
        redirect_to root_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_owner?
    @post.user.email == current_user.email
  end
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <%= link_to 'Blog', root_path, class: 'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "新文章", new_post_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "登出", destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else%>
        <li class="nav-item">
          <%= link_to "註冊", new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "登入", new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="search">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit" value="test">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/nav' %>
    </header>

    <main role="main" class="container-fluid">
      <div class="row">
        <div class="col-md-9" id="main">
          <% flash.each do |type, msg| %>
            <%= content_tag(:div, msg, class: "alert alert-#{type}",id: 'flash') %>
          <% end %>
          <%= yield %>
        </div>
        <div class="col-md-3" id="category" >
          <nav class="navbar flex-column">
            <% Post.tag_counts.each do |tag|%>
            <%= link_to "##{tag.name}", posts_path(tag_selected: tag.name) %>
            <% end %>
          </nav>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="row center">
  <div class="col-md-6">
    <%= simple_form_for(@post) do |f| %>
      <%= f.input :title %>
      <%= f.input :brief %>
      <%= f.input :content %>
      <%= f.input :tag_list%>
      <%= f.input :image %>
      <%= f.button :submit, yield(:btn_text) %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<% provide(:btn_text, '編輯')%>
<h1>編輯</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="card-columns">
  <% @posts.each do |post| %>
    <div class="card">
      <%= image_tag(post.image, alt: 'IMAGE')%>
      <div class="card-body">
        <h6 class="card-title"><%= post.title %></h6>
        <small class="card-text"><%= post.brief %></small>
      </div>
      <div class="card-footer">
        <%= link_to '查看更多', post_path(post), class: "btn btn-sm btn-secondary" %>
      </div>
    </div>
  <% end %>
    <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<% provide(:btn_text, '發布文章')%>
<h1>新文章</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="content_wrapper">
  <%= image_tag(@post.image ,alt: 'IMAGE')%>
  <h1><%= @post.title %></h1>
  <p><%= @post.content %></p>
  <p><%= @post.user.email %></p>
  <small><%= @post.created_at.localtime.strftime("撰寫於 %F ") %></small>
  <br>
  <% @post.tag_list.each do |tag_name| %>
    <small><%= "##{tag_name}" %></small>
  <% end %>
  <br>
  <% if user_signed_in? && post_owner? %>
    <%= link_to '編輯', edit_post_path(@post) %>
    <%= link_to '刪除', post_path(@post), method: :delete, data: {confirm: "刪除?"} %>
  <% end %>
</div>